Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,26 +9,61 @@ pr:
 pool:
   name: aws-self-hosted-agent
 
+variables:
+  AWS_SERVICE_CONNECTION: 'azure_user_SC' 
+
+parameters:
+- name: action
+  displayName: 'Select the Action to Perform'
+  type: string
+  default: 'apply'
+  values:
+  - apply
+  - destroy
+
+- name: workspace
+  displayName: 'Terraform Workspace Choice'
+  type: string
+  default: 'dev'
+  values:
+  - dev
+  - prod
+
 steps:
 - script: |
     echo Test => Hello, world!
   displayName: 'Test script'
 
-
 - task: AWSShellScript@1
   inputs:
-    awsCredentials: 'azure_user_SC'
+    awsCredentials: '$(AWS_SERVICE_CONNECTION)'
     regionName: 'us-east-1'
     scriptType: 'inline'
     inlineScript: |
       cd TerraformCode
-      ls
+      terraform init
+      
+      # Create or select Terraform workspace
+      terraform workspace select $(workspace) || terraform workspace new $(workspace)
+      
+      # Run Terraform plan for pull requests
       if [ "$(Build.Reason)" = "PullRequest" ]; then
-        terraform init
-        terraform plan
+        terraform plan -var-file=$(workspace)-variables.tfvars
+
       elif [ "$(Build.Reason)" = "IndividualCI" ]; then
-        terraform init
-        terraform plan
+        terraform plan -var-file=$(workspace)-variables.tfvars
+        #terraform apply -auto-approve -var-file=$(workspace)-variables.tfvars
+      
+      # # Run Terraform apply or destroy for manual runs
+      # elif [ "$(Build.Reason)" = "Manual" ] || [ "$(Build.Reason)" = "IndividualCI" ]; then
+      #   if [ "$(action)" = "apply" ]; then
+      #     terraform apply -auto-approve -var-file=$(workspace)-variables.tfvars
+      #   elif [ "$(action)" = "destroy" ]; then
+      #     terraform destroy -auto-approve -var-file=$(workspace)-variables.tfvars
+      #   else
+      #     echo "Invalid action selected. Please choose either 'apply' or 'destroy'."
+      #     exit 1
+      #   fi
       fi
   displayName: 'Run Terraform'
 
